import { savannahImage } from "../../media";

export const styles = {
  infoWindowContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    backgroundImage: `url(${savannahImage})`,
    backgroundSize: "cover",
    width: 400,
    height: 620,
    padding: "25px 0",
    position: "relative",
  },
  overlayContainer: {
    background: "#000000b8",
    width: "inherit",
    height: "100%",
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  title: {
    color: "#d78800",
    textShadow: "7px 6px 2px rgb(0 0 0 / 40%)",
    fontSize: "2.3rem",
  },
  displayImage: {
    height: 200,
    width: 200,
    borderRadius: 8,
  },
  imgAttributation: {
    color: "white",
    fontSize: ".5rem",
    a: {
      color: "white",
    },
    "a:WebkitAnyLink": {
      color: "white",
    },
  },
  infoLinesContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    width: "70%",
    margin: "13px auto 0px",
    padding: "10px 22px",
    fontSize: "1rem",
    background: "#ffe4c447",
    fontWeight: "bold",
    borderRadius: 4,
    boxShadow: "inset 1px 1px 19px 5px rgb(213 152 0 / 8%)",
    border: "5px rgb(255 255 255 / 24%)",
    borderStyle: "ridge",
  },
  infoLines: {
    color: "#f4ffc5",
    display: "flex",
    alignItems: "center",
    boxShadow: "rgb(215 136 0 / 8%) 10px 2px 20px 5px",
    backgroundColor: "rgb(215 136 0 / 8%)",
  },
  itemProps: {
    color: "#d78800",
    fontSize: "1.5rem",
    paddingLeft: 9,
    whiteSpace: "nowrap",
  },
  speciesText: {
    fontStyle: "italic",
    fontSize: "1.25rem",
    fontWeight: 400,
    color: "rgb(255 221 162)",
    fontFamily: "none",
  },
};
